In [3]:
#pip install numpy

In [4]:
import numpy as np

In [5]:
a=np.array(60)
print(a)
print(type(a))
print(a.ndim)

60
<class 'numpy.ndarray'>
0


In [6]:
b=np.array([1,2,3])
print(b)
print(type(b))
print(b.ndim)

[1 2 3]
<class 'numpy.ndarray'>
1


In [7]:
c=np.array([[1,2,4,5],[6,7,8,9]])
print(c)
print(type(c))
print(c.ndim)

[[1 2 4 5]
 [6 7 8 9]]
<class 'numpy.ndarray'>
2


In [10]:
d=np.array([[[1,2,3],[4,5,6]],
            [[7,8,9],[3,7,9]]])
print(d)
print(type(d))
print(d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 9]]]
<class 'numpy.ndarray'>
3


In [11]:
print(d[1][0][0])

7


In [12]:
print(d[1][1][2])

9


In [ ]:
#2 dimensions

In [13]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(type(c))
print(c.ndim)


[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [ ]:
#3 dimensions

In [14]:
d=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(d)
print(type(d))
print(d.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>
3


In [17]:
arr=np.array([1,2,3,4,5])
print(arr+10)
print(arr.mean())
print(arr.shape)

[11 12 13 14 15]
3.0
(5,)
